<?php

namespace Zepluf\Bundle\StoreBundle\Controller;

/**
 * This code has been auto-generated by the JMSDiExtraBundle.
 *
 * Manual changes to it will be lost.
 */
class AdminPluginController__JMSInjector
{
    public static function inject($container) {
        $instance = new \Zepluf\Bundle\StoreBundle\Controller\AdminPluginController();
        return $instance;
    }
}
