imports:
  - { resource: parameters.yml }

framework:
  translator: { fallback: %locale% }
  default_locale:  %locale%
  router:
    resource: "%kernel.root_dir%/config/routing.yml"
    strict_requirements: %kernel.debug%
  templating:
    engines: ['php', 'twig'] #assets_version: SomeVersionScheme
    loaders:  [storebundle.templating.template_loader, storebundle.templating.plugin_loader, storebundle.templating.bundle_loader]
  secret: %secret%

# Doctrine Configuration
doctrine:
  dbal:
    driver:   %database_driver%
    host:     %database_host%
    port:     %database_port%
    dbname:   %database_name%
    user:     %database_user%
    password: %database_password%
    charset:  UTF8

  orm:
    auto_generate_proxy_classes: %kernel.debug%
    auto_mapping: true

# Twig Configuration
twig:
  debug:            %kernel.debug%
  strict_variables: %kernel.debug%

monolog:
  handlers:
    main:
      type: fingers_crossed
      action_level: error
      handler:      nested
    nested:
      type:  stream
      path:  %kernel.logs_dir%/%kernel.environment%.log
      level: debug
    zencart:
      type: service
      id: StoreBundle.logger.zencart_handler
