parameters:
  plugins.root_dir: "%kernel.root_dir%/plugins"
  store.zencart_dir: "%kernel.root_dir%/../.."
  store.backend_dir: "%store.zencart_dir%/manager"
  store.current_template: "0007"
  store.template_dir: "%store.zencart_dir%/includes/templates"
  kernel.config_dir: "%kernel.root_dir%/config"
  web.dir: "%kernel.root_dir%/../web"
  web.cache_dir: "%web.dir%/cache"
  web.images_dir: "%web.dir%/images"

  locale: en

  database_driver:   pdo_mysql
  database_host:     localhost
  database_port:     ~
  database_name:     demo
  database_user:     simple_shop
  database_password: simple_shop
  table_prefix:      zen_

  mailer_transport:  smtp
  mailer_host:       localhost
  mailer_user:       ~
  mailer_password:   ~

  locale:            en
  secret:            asd214322dewd1e121eq
