<?php

namespace Proxies\__CG__\Zepluf\Bundle\StoreBundle\Entity;

/**
 * THIS CLASS WAS GENERATED BY THE DOCTRINE ORM. DO NOT EDIT THIS FILE.
 */
class Product extends \Zepluf\Bundle\StoreBundle\Entity\Product implements \Doctrine\ORM\Proxy\Proxy
{
    private $_entityPersister;
    private $_identifier;
    public $__isInitialized__ = false;
    public function __construct($entityPersister, $identifier)
    {
        $this->_entityPersister = $entityPersister;
        $this->_identifier = $identifier;
    }
    /** @private */
    public function __load()
    {
        if (!$this->__isInitialized__ && $this->_entityPersister) {
            $this->__isInitialized__ = true;

            if (method_exists($this, "__wakeup")) {
                // call this after __isInitialized__to avoid infinite recursion
                // but before loading to emulate what ClassMetadata::newInstance()
                // provides.
                $this->__wakeup();
            }

            if ($this->_entityPersister->load($this->_identifier, $this) === null) {
                throw new \Doctrine\ORM\EntityNotFoundException();
            }
            unset($this->_entityPersister, $this->_identifier);
        }
    }

    /** @private */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    
    public function getId()
    {
        if ($this->__isInitialized__ === false) {
            return (int) $this->_identifier["id"];
        }
        $this->__load();
        return parent::getId();
    }

    public function setType($type)
    {
        $this->__load();
        return parent::setType($type);
    }

    public function getType()
    {
        $this->__load();
        return parent::getType();
    }

    public function setName($name)
    {
        $this->__load();
        return parent::setName($name);
    }

    public function getName()
    {
        $this->__load();
        return parent::getName();
    }

    public function setDescription($description)
    {
        $this->__load();
        return parent::setDescription($description);
    }

    public function getDescription()
    {
        $this->__load();
        return parent::getDescription();
    }

    public function setIntroductionDate($introductionDate)
    {
        $this->__load();
        return parent::setIntroductionDate($introductionDate);
    }

    public function getIntroductionDate()
    {
        $this->__load();
        return parent::getIntroductionDate();
    }

    public function setSalesDiscontinuationDate($salesDiscontinuationDate)
    {
        $this->__load();
        return parent::setSalesDiscontinuationDate($salesDiscontinuationDate);
    }

    public function getSalesDiscontinuationDate()
    {
        $this->__load();
        return parent::getSalesDiscontinuationDate();
    }

    public function setAvailableDate($availableDate)
    {
        $this->__load();
        return parent::setAvailableDate($availableDate);
    }

    public function getAvailableDate()
    {
        $this->__load();
        return parent::getAvailableDate();
    }

    public function addPriceComponent(\Zepluf\Bundle\StoreBundle\Entity\PriceComponent $priceComponent)
    {
        $this->__load();
        return parent::addPriceComponent($priceComponent);
    }

    public function removePriceComponent(\Zepluf\Bundle\StoreBundle\Entity\PriceComponent $priceComponent)
    {
        $this->__load();
        return parent::removePriceComponent($priceComponent);
    }

    public function getPriceComponent()
    {
        $this->__load();
        return parent::getPriceComponent();
    }

    public function addTermType(\Zepluf\Bundle\StoreBundle\Entity\TermType $termType)
    {
        $this->__load();
        return parent::addTermType($termType);
    }

    public function removeTermType(\Zepluf\Bundle\StoreBundle\Entity\TermType $termType)
    {
        $this->__load();
        return parent::removeTermType($termType);
    }

    public function getTermType()
    {
        $this->__load();
        return parent::getTermType();
    }

    public function setManufacturer(\Zepluf\Bundle\StoreBundle\Entity\Organization $manufacturer = NULL)
    {
        $this->__load();
        return parent::setManufacturer($manufacturer);
    }

    public function getManufacturer()
    {
        $this->__load();
        return parent::getManufacturer();
    }

    public function setUnitOfMeasurement(\Zepluf\Bundle\StoreBundle\Entity\UnitOfMeasurement $unitOfMeasurement = NULL)
    {
        $this->__load();
        return parent::setUnitOfMeasurement($unitOfMeasurement);
    }

    public function getUnitOfMeasurement()
    {
        $this->__load();
        return parent::getUnitOfMeasurement();
    }

    public function getProductFeatureApplication()
    {
        $this->__load();
        return parent::getProductFeatureApplication();
    }

    public function getProductCategory()
    {
        $this->__load();
        return parent::getProductCategory();
    }

    public function addProductFeatureApplication(\Zepluf\Bundle\StoreBundle\Entity\ProductFeatureApplication $productFeatureApplication)
    {
        $this->__load();
        return parent::addProductFeatureApplication($productFeatureApplication);
    }

    public function removeProductFeatureApplication(\Zepluf\Bundle\StoreBundle\Entity\ProductFeatureApplication $productFeatureApplication)
    {
        $this->__load();
        return parent::removeProductFeatureApplication($productFeatureApplication);
    }

    public function addProductCategory(\Zepluf\Bundle\StoreBundle\Entity\ProductCategory $productCategory)
    {
        $this->__load();
        return parent::addProductCategory($productCategory);
    }

    public function removeProductCategory(\Zepluf\Bundle\StoreBundle\Entity\ProductCategory $productCategory)
    {
        $this->__load();
        return parent::removeProductCategory($productCategory);
    }


    public function __sleep()
    {
        return array('__isInitialized__', 'id', 'type', 'name', 'description', 'introductionDate', 'salesDiscontinuationDate', 'availableDate', 'priceComponent', 'termType', 'manufacturer', 'unitOfMeasurement', 'productFeatureApplication', 'productCategory');
    }

    public function __clone()
    {
        if (!$this->__isInitialized__ && $this->_entityPersister) {
            $this->__isInitialized__ = true;
            $class = $this->_entityPersister->getClassMetadata();
            $original = $this->_entityPersister->load($this->_identifier);
            if ($original === null) {
                throw new \Doctrine\ORM\EntityNotFoundException();
            }
            foreach ($class->reflFields as $field => $reflProperty) {
                $reflProperty->setValue($this, $reflProperty->getValue($original));
            }
            unset($this->_entityPersister, $this->_identifier);
        }
        
    }
}