<?php

namespace Proxies\__CG__\Zepluf\Bundle\StoreBundle\Entity;

/**
 * THIS CLASS WAS GENERATED BY THE DOCTRINE ORM. DO NOT EDIT THIS FILE.
 */
class OrderItem extends \Zepluf\Bundle\StoreBundle\Entity\OrderItem implements \Doctrine\ORM\Proxy\Proxy
{
    private $_entityPersister;
    private $_identifier;
    public $__isInitialized__ = false;
    public function __construct($entityPersister, $identifier)
    {
        $this->_entityPersister = $entityPersister;
        $this->_identifier = $identifier;
    }
    /** @private */
    public function __load()
    {
        if (!$this->__isInitialized__ && $this->_entityPersister) {
            $this->__isInitialized__ = true;

            if (method_exists($this, "__wakeup")) {
                // call this after __isInitialized__to avoid infinite recursion
                // but before loading to emulate what ClassMetadata::newInstance()
                // provides.
                $this->__wakeup();
            }

            if ($this->_entityPersister->load($this->_identifier, $this) === null) {
                throw new \Doctrine\ORM\EntityNotFoundException();
            }
            unset($this->_entityPersister, $this->_identifier);
        }
    }

    /** @private */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    
    public function getId()
    {
        if ($this->__isInitialized__ === false) {
            return (int) $this->_identifier["id"];
        }
        $this->__load();
        return parent::getId();
    }

    public function setSequenceId($sequenceId)
    {
        $this->__load();
        return parent::setSequenceId($sequenceId);
    }

    public function getSequenceId()
    {
        $this->__load();
        return parent::getSequenceId();
    }

    public function setQuantity($quantity)
    {
        $this->__load();
        return parent::setQuantity($quantity);
    }

    public function getQuantity()
    {
        $this->__load();
        return parent::getQuantity();
    }

    public function setUnitPrice($unitPrice)
    {
        $this->__load();
        return parent::setUnitPrice($unitPrice);
    }

    public function getUnitPrice()
    {
        $this->__load();
        return parent::getUnitPrice();
    }

    public function setEstimatedDeliveryDate($estimatedDeliveryDate)
    {
        $this->__load();
        return parent::setEstimatedDeliveryDate($estimatedDeliveryDate);
    }

    public function getEstimatedDeliveryDate()
    {
        $this->__load();
        return parent::getEstimatedDeliveryDate();
    }

    public function setItemDescription($itemDescription)
    {
        $this->__load();
        return parent::setItemDescription($itemDescription);
    }

    public function getItemDescription()
    {
        $this->__load();
        return parent::getItemDescription();
    }

    public function setComment($comment)
    {
        $this->__load();
        return parent::setComment($comment);
    }

    public function getComment()
    {
        $this->__load();
        return parent::getComment();
    }

    public function setType($type)
    {
        $this->__load();
        return parent::setType($type);
    }

    public function getType()
    {
        $this->__load();
        return parent::getType();
    }

    public function setProduct(\Zepluf\Bundle\StoreBundle\Entity\Product $product = NULL)
    {
        $this->__load();
        return parent::setProduct($product);
    }

    public function getProduct()
    {
        $this->__load();
        return parent::getProduct();
    }

    public function setOrder(\Zepluf\Bundle\StoreBundle\Entity\Order $order = NULL)
    {
        $this->__load();
        return parent::setOrder($order);
    }

    public function getOrder()
    {
        $this->__load();
        return parent::getOrder();
    }

    public function setOrderItem(\Zepluf\Bundle\StoreBundle\Entity\OrderItem $orderItem = NULL)
    {
        $this->__load();
        return parent::setOrderItem($orderItem);
    }

    public function getOrderItem()
    {
        $this->__load();
        return parent::getOrderItem();
    }


    public function __sleep()
    {
        return array('__isInitialized__', 'id', 'sequenceId', 'quantity', 'unitPrice', 'estimatedDeliveryDate', 'itemDescription', 'comment', 'type', 'product', 'order', 'orderItem');
    }

    public function __clone()
    {
        if (!$this->__isInitialized__ && $this->_entityPersister) {
            $this->__isInitialized__ = true;
            $class = $this->_entityPersister->getClassMetadata();
            $original = $this->_entityPersister->load($this->_identifier);
            if ($original === null) {
                throw new \Doctrine\ORM\EntityNotFoundException();
            }
            foreach ($class->reflFields as $field => $reflProperty) {
                $reflProperty->setValue($this, $reflProperty->getValue($original));
            }
            unset($this->_entityPersister, $this->_identifier);
        }
        
    }
}