initialized: true
installed:
  - riPlugin
  - riCache
  - riZCAdmin
  - riCjLoader
activated:
  - riPlugin
  - riCache
  - riZCAdmin
  - riCjLoader
core:
  - riPlugin
  - riCache
  - riZCAdmin
  - riCjLoader
backend:
  - riCache
  - riZCAdmin
  - riCjLoader
frontend:
  - riCache
  - riCjLoader
