installed:
    - riPlugin
    - riCache
    - riZCAdmin
    - riCjLoader
    - riResultList
    - riBanner
activated:
    - riPlugin
    - riCache
    - riZCAdmin
    - riCjLoader
    - riResultList
core:
    - riPlugin
    - riCache
    - riZCAdmin
    - riCjLoader
    - riResultList
backend:
    - riPlugin
    - riCache
    - riZCAdmin
    - riCjLoader
    - riResultList
frontend:
    - riPlugin
    - riCache
    - riCjLoader
    - riResultList
